SELECT ENAME, DNAME, SAL
FROM EMP
JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE SAL > 1000 AND SAL < 2000;

SELECT COUNT(*)
FROM EMP
WHERE DEPTNO = 30 AND SAL IS NOT NULL AND COMM IS NOT NULL;

SELECT ENAME, SAL
FROM EMP
JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE SAL >= 1000 AND LOC = 'DALLAS';

SELECT EMP.ENAME, DEPT.DNAME, EMP.SAL
FROM EMP
JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE EMP.SAL > 1000 AND EMP.SAL < 2000;

SELECT DEPTNO, AVG(SAL) AS AVG_SALARY, COUNT(*) AS NUM_EMPLOYEES
FROM EMP
GROUP BY DEPTNO;