CREATE TABLE DEPT (
    DEPTNO SERIAL PRIMARY KEY,
    DNAME VARCHAR(255),
    LOC VARCHAR(255)
);

CREATE TABLE EMP (
    EMPNO SERIAL PRIMARY KEY,
    ENAME VARCHAR(255) NOT NULL,
    JOB VARCHAR(255) NOT NULL,
    MGR INTEGER,
    HIREDATE DATE NOT NULL,
    SAL INTEGER NOT NULL,
    COMM INTEGER NOT NULL,
    DEPTNO INTEGER NOT NULL,
    FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO)
);
